### ISSUE TITLE
not able to use

### ISSUE THREAD

**Issue by ManishLSN** [manoj30808/outlook-calendar-event#1]
here i used cmd,
`$ composer require msppack/outlook-calendar
C:/xampp/php/php.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory`

> error while loading shared libraries: ?: cannot open shared object file: No such file or directory

**Comment by manoj30808** [comment]
this error you got during composer update?

**Comment by ManishLSN** [comment]
Yes, I got this at time of using the repository on my local machine. and I also wrote the cmd I was using.

**Comment by manoj30808** [comment]
Ok give me some time let you know update

**Comment by manoj30808** [comment]
I tried in my local system it's working fine, please update your system composer or try the latest version.
